Makefile, README, Clean-up
HaikuArchives/TileSaver pull request #1
Opened 2018-11-29 00:06 UTC by bach5000

Some changes that come with this pull request:
* An updated Makefile
* Added a README
* Moved source files to the "src" directory
* Added a screenshot

2018-11-29 05:56 UTC, humdingerb commented
To not let you off too easily for this task, how about cleaning up the source according to the [Haiku Coding Style](https://www.haiku-os.org/development/coding-guidelines)?  :)

2018-11-29 07:00 UTC, scottmc commented
Also, once this is merged it'd be nice to also see a matching recipe at Haikuports for it.

2018-11-29 07:32 UTC, owenca commented
> To not let you off too easily for this task, how about cleaning up the source according to the [Haiku Coding Style](https://www.haiku-os.org/development/coding-guidelines)? :)

@bach5000 You might want to use `haiku-format` found [here](https://github.com/owenca/haiku-format).

2018-11-29 17:32 UTC, bach5000 commented
@humdingerb @scottmc @owenca:
Cleaned up the source!

2018-11-29 17:46 UTC, humdingerb requested changes
* in RandomColor.cpp, l.29 ff: No need for the curly brackets, also remove empty lines

* Use Koder to find unneeded whitespaces.

* In TileSaver.cpp,
   l.104: too much indentation. Just one more than the previous line.
   l.106: too much indentation. Just one more than the previous line. Re-wrap to 80 chars.
   l.134: no need for the curly brackets

* The "*" of pointers belong to the type, e.g. `BView *pConfigView` -> `BView* pConfigView`

* Two blank lines between functions

2018-11-29 18:15 UTC, bach5000 commented
@humdingerb Ah. Will fix now :)

2018-11-29 18:35 UTC, bach5000 commented
@humdingerb I think I got all the things you mentioned in the review... Not sure though :)

2018-11-29 18:40 UTC, humdingerb requested changes
There are still a few stray tabs in TileSaver.cpp|h.
Also check indentation on TileSaver.h so the function/variable names line up. (4 spaces per tab)
I recommend Koder esp. for the whitespaces.

2018-11-29 18:40 UTC, humdingerb commented on src/TileSaver.cpp
> +				"\n"
You can indent all the text one tab more that line 110 and re-wrap to 80 chars.

2018-11-29 18:40 UTC, humdingerb commented on src/TileSaver.cpp
> +				"to redistribute it under certain conditions."
Maybe add a "`\n`" at the end of this line.

2018-11-29 20:06 UTC, bach5000 commented
@humdingerb May have to wait until night to be able to use Koder... but will fix :)

2018-11-30 00:11 UTC, bach5000 commented
@humdingerb You're right... I can see a lot of errors when I open these files up with Koder... yikes.
But I fixed the whitespace issues! So I'm going to push those commits right now.

2018-11-30 15:41 UTC, merged

2018-11-30 15:42 UTC, humdingerb commented
Thanks. I did the re-wrapping of the config text myself. Hope you don't mind.

2018-11-30 16:16 UTC, bach5000 commented
@humdingerb Sorry for making you do work :(